---
- name: RHCE Practice Playbook 1
  hosts: localhost
  remote_user: shoughtsky
  # become: True

  tasks:
  - name:
    command:
      cmd: echo {{ item }}
    with_items:
      - Green
      - Yellow
      - Purple
    register: echo
  - debug:
      msg: "{{ echo }}"
      
