---
- name: Bootstrap Control Node
  hosts: control
  gather_facts: true
  become: true
  tasks:
  - name: install required packages
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
    - python-pip

  - name: Create Ansible Inventory Directory
    file:
      path: /etc/ansible/inventory
      state: directory
      mode: '0775'
    with_items:
    - /etc/ansible    
    - /etc/ansible/inventory
    - /etc/ansible/playbooks

  - name: create ansible configuration file
    copy:
      content: |
        [defaults]
        inventory = /etc/ansible/inventory/hosts
        host_key_checking = False
        forks = 50
      dest: /etc/ansible/ansible.cfg
      mode: '0664'

