---
- hosts: database
  remote_user: shoughtsky
  become: True
  tasks:
  - name: create database_list
    linefile:
      line: dev,test,qa,prod
      path: /mnt/mysql_backups/database_list
      state: present

  - name: gzip database_list
    archive:
      path: /mnt/mysql_backups/database_list
      dest: /mnt/mysql_backups/archive.gz
      format: gz
