- hosts: proxy
  remote_user: shoughtsky
  become: True
  tasks:
    - name: Run cron job
      cron:
        name: update time
        hour: '*/1'
        job: "date >> /var/log/time.log"

        
    