- hosts: all
  remote_user: shoughtsky
  become: True
  tasks:
    - name:
      template:
        src: templates/mysql56-community.j2
        dest: /etc/yum.repos.d/mysql56-community.j2
        owner: root
        group: root
        mode: 0664