--- 
- hosts: proxy
  remote_user: shoughtsky
  become: True

  vars:
    haproxy_socket: '80'
    haproxy_user: root
    haproxy_group: root

    haproxy_backend_servers:
      - name: app1
        address: 127.0.0.1:80

  roles:
    - role: geerlingguy.haproxy
  
  tasks:
    - name: Allow http through firewalld
      firewalld:
        zone: dmz
        service: http
        permanent: yes
        state: enabled
