---
- name: RHCE Practice Playbook 1
  hosts: localhost
  remote_user: shoughtsky
  tasks:
  - name: Task7/Conditional
    command:
      cmd: echo {{ item }}
    with_items:
      - Green
      - Yellow
      - Purple
    register: echo
  - debug:
      msg: "{{ echo }}"
  

- name: RHCE Practice Playbook 1
  hosts: deadhosts
  remote_user: shoughtsky
  gather_facts: false
  tasks:
  - name: Task8/Handling Task Failure
    command:
      cmd: /usr/bin/true
    register: task8_output
    ignore_unreachable: True
    



      
