- hosts: web
  remote_user: shoughtsky
  become: True
  tasks:
  - name: add alice
    user:
      name: alice
      state: present
      uid: 1201
      ssh_key_file:
    when: "'web' in group_names"
  - name: add vincent
    user:
      name: vincent
      state: present
      uid: 1202
      ssh_key_file:
    when: "'web' in group_names"
  - name: add sandy
    user:
      name: sandy
      state: present
      uid: 2201
      ssh_key_file:
    when: "'database' in group_names"
  - name: add patrick
    user:
      name: patrick
      state: present
      uid: 2202
      ssh_key_file:
    when: "'database' in group_names"