---
- hosts: all
  remote_user: shoughtsky
  become: True
  tasks:
    - name: Create directory for ansible custom facts
      ansible.builtin.file:
        state: directory
        recurse: true
        path: /etc/ansible/facts.d

    - name: Install custom fact
      ansible.builtin.copy:
        src: customfacts.fact
        dest: /etc/ansible/facts.d

    - name: Re-read facts after adding custom fact
      ansible.builtin.setup:
        filter: ansible_local
    
  - debug:
      msg: "{{ ansible_local.custom.customfacts }}"