---
# tasks file for RHCE motd
- name: update existing motd
  become: True
  template:
    src: templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0664
    backup: yes

      