---
- hosts: all
  remote_user: shoughtsky
  become: True
  tasks:
  - name: check for mem reqs
    fail:
      msg: Server memory less than 2048MB
    when: ansible_memtotal_mb < '2048'
      

  - name: configure sysctl swappiness
    sysctl:
      name: vm.swappiness
      value: '10'
      state: present
    when: ansible_memtotal_mb >= '2048'
